parameters:
    netgen.ezforms.form.fieldtype_handler.enhancedezbinaryfile.class: Netgen\Bundle\EnhancedBinaryFileBundle\Form\FieldTypeHandler\EnhancedFile

services:
    netgen.ezforms.form.fieldtype_handler.enhancedezbinaryfile:
        class: %netgen.ezforms.form.fieldtype_handler.enhancedezbinaryfile.class%
        arguments:
            - @ezpublish.config.resolver
        tags:
            - {name: netgen.ezforms.form.fieldtype_handler, alias: enhancedezbinaryfile}
