parameters:
  mime.default.doc.Types:
    - application/msword
# the following entry did not exist in module.ini.append but it's a likely feature request
# so just uncomment when it's needed
#
#  mime.default.docx.Types:
#    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  mime.default.gif.Types:
    - image/gif
  mime.default.jpg.Types:
    - image/jpeg
  mime.default.jpe.Types:
    - image/jpeg
  mime.default.jpeg.Types:
    - image/jpeg
  mime.default.png.Types:
    - image/png
  mime.default.sxw.Types:
    - application/vnd.sun.xml.writer
  mime.default.txt.Types:
    - text/plain
