parameters:
  mime.default.3gp.Types:
    - video/3gpp
    - audio/3gpp
  mime.default.af.Types:
    - audio/aiff
    - audio/x-aiff
    - audio/x-pn-aiff
  mime.default.ai.Types:
    - application/postscript
  mime.default.aiff.Types:
    - audio/aiff
    - audio/x-aiff
    - audio/x-pn-aiff
  mime.default.asc.Types:
    - text/plain
  mime.default.asf.Types:
    - video/x-ms-asf
  mime.default.au.Types:
    - audio/basic
    - audio/x-pn-au
  mime.default.avi.Types:
    - video/x-msvideo

  mime.default.jpg.Types:
    - image/jpeg
  mime.default.jpe.Types:
    - image/jpeg
  mime.default.jpeg.Types:
    - image/jpeg

  # BEGIN ngmore/jwplayer additions
  mime.default.m4v.Types:
    - video/mp4
  mime.default.f4v.Types:
    - video/mp4
  mime.default.flv.Types:
    - video/flv
  # END ngmore/jwplayer additions

