system:
    default:
        fielddefinition_edit_templates:
            -
                template: "@NetgenEnhancedBinaryFileBundle/admin/field_types.html.twig"
        field_templates:
            -
                template: "@NetgenEnhancedBinaryFileBundle/content_fields.html.twig"
