services:
    ezpublish.fieldType.enhancedezbinaryfile:
        class: Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\EnhancedBinaryFile\Type
        parent: ezpublish.fieldType
        arguments:
            - "@ezpublish.core.io.mimetypedetector"
            - "@ezpublish.config.resolver"
        tags:
            - { name: ezpublish.fieldType, alias: enhancedezbinaryfile }

    ezpublish.fieldType.enhancedezbinaryfile.storage_gateway:
        class: eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler.gateway, alias: enhancedezbinaryfile, identifier: LegacyStorage }

    ezpublish.fieldType.enhancedezbinaryfile.form_mapper:
        class: Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\EnhancedBinaryFile\FormMapper
        arguments:
            - "@ezpublish.api.service.field_type"
            - "@ezrepoforms.config_resolver.max_upload_size"
        tags:
            - { name: ez.fieldFormMapper.definition, fieldType: enhancedezbinaryfile }
