services:
    ezpublish.enhancedezbinaryfile.external_storage_handler:
            class: eZ\Publish\Core\FieldType\BinaryBase\BinaryBaseStorage
            arguments:
                - "@ezpublish.fieldType.ezbinaryfile.storage_gateway"
                - "@ezpublish.fieldType.ezbinaryfile.io_service"
                - "@ezpublish.fieldType.ezbinaryfile.pathGenerator"
                - "@ezpublish.core.io.mimeTypeDetector"
            tags:
                - { name: ezpublish.fieldType.externalStorageHandler, alias: enhancedezbinaryfile }
