services:
    Netgen\Bundle\EnhancedBinaryFileBundle\FieldHandler\EnhancedBinaryFileHandler:
        autowire: true
        arguments:
            - "@ezpublish.core.io.service"
        tags:
            - { name: netgen_information_collection.field_handler.custom }
