services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\EnhancedBinaryFile\FieldTypeFormMapper:
        tags:
        - { name: ezplatform.field_type.form_mapper.definition, fieldType: enhancedezbinaryfile }

    Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\EnhancedBinaryFile\FieldValueFormMapper:
        tags:
            - { name: ezplatform.field_type.form_mapper.value, fieldType: enhancedezbinaryfile }

    Netgen\Bundle\EnhancedBinaryFileBundle\Form\Type\EnhancedBinaryFileFieldType:
        tags:
            - { name: 'form.type' }