netgen_enhancedezbinaryfile.route.download_binary_file:
    path: /netgen/enhancedezbinaryfile/download/{infocollectionAttributeId}
    defaults: { _controller: netgen_enhancedezbinaryfile.controller.download:downloadCollectedEnhancedEzBinaryFileAction }
    methods: [GET]