services:
    Netgen\Bundle\EnhancedBinaryFileBundle\Controller\DownloadController:
        autoconfigure: true
        tags: [controller.service_arguments]
        calls:
            - [ setContainer, [ "@service_container" ] ]
        arguments:
            - "@netgen_information_collection.repository.ez_info_collection_attribute"
            - "@netgen_information_collection.repository.ez_info_collection"
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
