parameters:
  ezpublish.fieldType.enhancedezbinaryfile.converter.class: Netgen\Bundle\EnhancedBinaryFileBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Converter


services:
  ezpublish.fieldType.enhancedezbinaryfile.converter:
    class: %ezpublish.fieldType.enhancedezbinaryfile.converter.class%
    tags:
        - {name: ezpublish.storageEngine.legacy.converter, alias: enhancedezbinaryfile}
