<?php

namespace Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\DataTransformer;

use eZ\Publish\API\Repository\FieldType;
use eZ\Publish\Core\FieldType\Value;
use EzSystems\EzPlatformContentForms\FieldType\DataTransformer\AbstractBinaryBaseTransformer;
use EzSystems\EzPlatformContentForms\FieldType\DataTransformer\BinaryFileValueTransformer;
use Symfony\Component\Form\DataTransformerInterface;

class EnhancedBinaryFileValueTransformer extends BinaryFileValueTransformer
{
    /**
     * @param FieldType $fieldType
     * @param Value|null $initialValue
     * @param string $valueClass
     */
    public function __construct(FieldType $fieldType, ?Value $initialValue, $valueClass)
    {
        $this->fieldType = $fieldType;
        $this->initialValue = $initialValue;
        $this->valueClass = $valueClass;
    }

    public function reverseTransform($value)
    {
        if (null === $value['file']) {
            return null;
        }

        return parent::reverseTransform($value); // TODO: Change the autogenerated stub
    }
}